"""
Name separators configuration.
"""

LAYER_NAMES_SEPARATOR = "__"
SOLID_EARTH_NUMERICAL_MODEL_PART_NAMES_SEPARATOR = 5 * "_"
SOLID_EARTH_NUMERICAL_MODEL_PART_NAME_FROM_PARAMETERS_SEPARATOR = 4 * "_"
LAYERS_SEPARATOR = "___"
VALUES_SEPARATOR = "__"
